name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Ensures the token isn't passed to actions

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version you need

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build the application
      - name: Build
        run: npm run build  # Ensure your package.json has a build script

      # Step 5: Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Adjust if your build output directory is different
          publish_branch: gh-pages  # The branch GitHub Pages is set to serve from
          commit_message: "Deploying updates to GitHub Pages"
